// components/MissionPlanner/PlannerDeliverablesView.tsx
'use client';

import React from 'react';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { PlannerDeliverables } from '@/lib/mission/types';
import { FileText, MapPin, Zap, ShieldCheck, Leaf, Compass, ListOrdered } from 'lucide-react';

interface PlannerDeliverablesViewProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  deliverables?: PlannerDeliverables;
  missionId: string;
}

export function PlannerDeliverablesView({
  open,
  onOpenChange,
  deliverables,
  missionId,
}: PlannerDeliverablesViewProps) {
  if (!deliverables) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-3xl bg-card border shadow-2xl rounded-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader className="space-y-1 border-b border-border pb-3">
          <div className="flex items-center space-x-2">
            <Badge className="bg-slate-900 text-emerald-400 border-slate-700 font-mono text-xs">
              {missionId}
            </Badge>
            <Badge variant="outline" className="bg-sky-500/10 text-sky-400 border-sky-500/30 text-xs font-mono">
              Planner Agent Deliverables
            </Badge>
          </div>
          <DialogTitle className="text-xl font-extrabold tracking-tight flex items-center gap-2 text-foreground">
            <FileText className="w-5 h-5 text-sky-400" />
            Autonomous Path Planning Engineering Artifacts
          </DialogTitle>
          <DialogDescription className="text-xs text-muted-foreground">
            First-class engineering deliverables generated by Agent 1 (Mission Planning Studio) and persisted to shared mission.
          </DialogDescription>
        </DialogHeader>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 py-3 text-xs">
          {/* 1. Boundary Report */}
          <Card className="p-4 border bg-background/60 rounded-xl space-y-2">
            <div className="flex items-center space-x-2 text-emerald-400 font-bold border-b border-border/60 pb-1.5">
              <MapPin className="w-4 h-4" />
              <span>1. Field Boundary Report</span>
            </div>
            <div className="space-y-1 font-mono text-[11px] text-muted-foreground">
              <p>• Surface Area: <span className="text-foreground font-bold">{deliverables.boundaryReport.acres} Acres</span></p>
              <p>• Perimeter: <span className="text-foreground font-bold">{deliverables.boundaryReport.perimeterMeters} meters</span></p>
              <p>• Vertices: <span className="text-foreground font-bold">{deliverables.boundaryReport.pointCount} Polygon Points</span></p>
              <p>• Geometry Status: <span className="text-emerald-400 font-bold">VALID & CLOSED</span></p>
            </div>
          </Card>

          {/* 2. Coverage Plan */}
          <Card className="p-4 border bg-background/60 rounded-xl space-y-2">
            <div className="flex items-center space-x-2 text-sky-400 font-bold border-b border-border/60 pb-1.5">
              <Compass className="w-4 h-4" />
              <span>2. Boustrophedon Coverage Plan</span>
            </div>
            <div className="space-y-1 font-mono text-[11px] text-muted-foreground">
              <p>• Optimal Sweep Angle: <span className="text-foreground font-bold">{deliverables.coveragePlan.sweepAngleDeg}°</span></p>
              <p>• Parallel Sweep Lanes: <span className="text-foreground font-bold">{deliverables.coveragePlan.laneCount} Lanes</span></p>
              <p>• Total Coverage: <span className="text-foreground font-bold">{deliverables.coveragePlan.coveragePct}% Field Surface</span></p>
              <p>• Targeted Mode: <span className="text-foreground font-bold">{deliverables.coveragePlan.isSpotSpray ? 'Spot Treatment' : 'Full Uniform Sweep'}</span></p>
            </div>
          </Card>

          {/* 3. Waypoint Set */}
          <Card className="p-4 border bg-background/60 rounded-xl space-y-2">
            <div className="flex items-center space-x-2 text-purple-400 font-bold border-b border-border/60 pb-1.5">
              <ListOrdered className="w-4 h-4" />
              <span>3. Autonomous Waypoint Set</span>
            </div>
            <div className="space-y-1 font-mono text-[11px] text-muted-foreground">
              <p>• Waypoints Count: <span className="text-foreground font-bold">{deliverables.waypointSet.totalWaypoints} Points</span></p>
              <p>• Flight Altitude: <span className="text-foreground font-bold">{deliverables.waypointSet.altitudeMeters} meters AGL</span></p>
              <p>• Takeoff WP: <span className="text-foreground font-bold">WP#1 (0.0, 0.0)</span></p>
              <p>• Landing WP: <span className="text-foreground font-bold">WP#{deliverables.waypointSet.totalWaypoints} (Return to Home)</span></p>
            </div>
          </Card>

          {/* 4. Battery & Energy Analysis */}
          <Card className="p-4 border bg-background/60 rounded-xl space-y-2">
            <div className="flex items-center space-x-2 text-amber-400 font-bold border-b border-border/60 pb-1.5">
              <Zap className="w-4 h-4" />
              <span>4. Battery & Energy Telemetry</span>
            </div>
            <div className="space-y-1 font-mono text-[11px] text-muted-foreground">
              <p>• Estimated Duration: <span className="text-foreground font-bold">{deliverables.batteryAnalysis.estimatedTimeMin} min ({deliverables.batteryAnalysis.estimatedTimeSec}s)</span></p>
              <p>• Battery Consumption: <span className="text-foreground font-bold">{deliverables.batteryAnalysis.batteryDrawPct}% Discharge</span></p>
              <p>• Total Distance: <span className="text-foreground font-bold">{deliverables.batteryAnalysis.flightDistanceMeters} meters</span></p>
              <p>• Safety Margin: <span className="text-emerald-400 font-bold">{deliverables.batteryAnalysis.batteryMarginPct}% Reserve</span></p>
            </div>
          </Card>

          {/* 5. Feasibility Report */}
          <Card className="p-4 border bg-background/60 rounded-xl space-y-2">
            <div className="flex items-center space-x-2 text-teal-400 font-bold border-b border-border/60 pb-1.5">
              <ShieldCheck className="w-4 h-4" />
              <span>5. Mission Feasibility Report</span>
            </div>
            <div className="space-y-1 font-mono text-[11px] text-muted-foreground">
              <p>• Feasibility Rating: <span className="text-emerald-400 font-bold">{deliverables.feasibilityReport.feasibilityStatus}</span></p>
              <p>• Wind Limit: <span className="text-foreground font-bold">{deliverables.feasibilityReport.windToleranceKmh} km/h max</span></p>
              <p>• Safety Buffer: <span className="text-foreground font-bold">{deliverables.feasibilityReport.safetyBufferMeters}m perimeter offset</span></p>
              <p className="text-[10px] font-sans text-muted-foreground italic mt-1">{deliverables.feasibilityReport.recommendation}</p>
            </div>
          </Card>

          {/* 6. Sustainability Report */}
          <Card className="p-4 border bg-background/60 rounded-xl space-y-2">
            <div className="flex items-center space-x-2 text-emerald-400 font-bold border-b border-border/60 pb-1.5">
              <Leaf className="w-4 h-4" />
              <span>6. SDG 12 & 13 Impact Report</span>
            </div>
            <div className="space-y-1 font-mono text-[11px] text-muted-foreground">
              <p>• Distance Reduced: <span className="text-emerald-400 font-bold">{deliverables.sustainabilityReport.distanceReductionMeters} meters</span></p>
              <p>• Battery Energy Saved: <span className="text-emerald-400 font-bold">{deliverables.sustainabilityReport.batterySavedPct}% energy</span></p>
              <p>• CO2 Avoided: <span className="text-emerald-400 font-bold">{deliverables.sustainabilityReport.co2AvoidedKg} kg CO2</span></p>
              <p>• Primary Goals: <span className="text-emerald-400 font-bold">SDG 13 (Climate Action) & SDG 12</span></p>
            </div>
          </Card>
        </div>
      </DialogContent>
    </Dialog>
  );
}
